### ISSUE TITLE
[FEEDBACK] Add ability to reposition overlay notifications

### ISSUE THREAD

**Issue by SalbugVR** [nnaaa-vr/XSOverlay-VRChat-Parser#1]
Having the notifications pop up close to the center of your view causes them to be a bit in the way. Being able to reposition them. say for example, closer to the bottom on the same level as VRC's mic icon would be a nice improvement.

**Comment by nnaaa-vr** [comment]
That's all configurable in XSOverlay. Go to the settings panel, and then to notifications tab. You can change the position and scale there. 

If you want to change opacity, how long specific notifications stick around, and things like that, that can be done in the parser config -- visit LocalLow\XSOverlay VRChat Parser\config.json and there's a bunch of options you can adjust there. 

Please let me know if this solves your problem. Thanks.

**Comment by SalbugVR** [comment]
Yeah, that's entirely on me lol. Just came to that realization while reading through the XSO documentation.
