### ISSUE TITLE
Not seeing config.json

### ISSUE THREAD

**Issue by GeneralFriendly** [nnaaa-vr/XSOverlay-VRChat-Parser#14]
[Edit:   This is a documentation error.   Found it under the proper path of AppData\LocalLow\XSOverlay VRChat Parser]

The wiki page mentions:

%AppData%\\..\LocalLow\VRChat\vrchat\config.json

as a place to find additional configuration settings.

I'm not seeing it at that location.  I installed from the .zip file.

Thanks

**Comment by nnaaa-vr** [comment]
The config file is generated by the application when it's first run, but you appear to have noticed a mistake in the README. It's not in \LocalLow\VRChat\vrchat\ , it's in \LocalLow\XSOverlay VRChat Parser\ . I'll fix the readme.
