### ISSUE TITLE
Join/Leave group batching not working as intended

### ISSUE THREAD

**Issue by SalbugVR** [nnaaa-vr/XSOverlay-VRChat-Parser#5]
Group batching keeps listing only one person at a time whenever the notification pops up. Others have noticed it as well.

Here's a video example of what it looks like.
https://drive.google.com/file/d/11HrFeMv9lRocw5RBCXYSMHu7cblIDlNb/view?usp=sharing

**Comment by nnaaa-vr** [comment]
DId you update to v0.21? I released it shortly after 0.2 to address that problem specifically.

**Comment by SalbugVR** [comment]
Okay, yeah never mind that is my bad. I could've sworn I had downloaded v0.21 but looks like I was wrong. ^^;
I will let Ruuubick know they should update as well.

**Comment by nnaaa-vr** [comment]
Yeah if you still continue to have issues with it let me know though, I dogfood the parser but rarely end up in a scenario for batching to be triggered.

**Comment by SalbugVR** [comment]
Got Community Meetup in VRC tomorrow afternoon so will be the perfect opportunity to test it out. I'll let you know if any issues crop up. ^^
